const dadJokes = [
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I used to play piano by ear, but now I use my hands!",
    "What do you call someone with no body and no nose? Nobody knows!",
    "How does a penguin build its house? Igloos it together!",
    "I'm friends with all the letters of the alphabet. I don't know Y!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "I'm on a seafood diet. I see food and I eat it!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "I don't trust stairs. They're always up to something!",
    "What do you call a fake noodle? An impasta!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "Why did the math book look sad? Because it had too many problems!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "How does a penguin build its house? Igloos it together!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "I don't trust stairs. They're always up to something!",
    "What do you call a fake noodle? An impasta!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "Why did the math book look sad? Because it had too many problems!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "What did one hat say to the other hat? You stay here, I'll go on ahead!",];

    module.exports = {dadJokes};